library(MASS)
data(Boston)
boxplot(medv ~ chas, data = Boston)
model_chas <- lm(medv ~ chas, data = Boston)
anova(model_chas)

#(b)
boxplot(medv ~ rad, data = Boston)
model_rad <- lm(medv ~ rad, data = Boston)
anova(model_rad)

#(c)
boxplot(medv ~ rad*chas, data = Boston)
interaction.plot( Boston$rad, Boston$chas, Boston$medv, fixed = TRUE, col = 1:9, lwd = 2) 
model_rad_chas <- lm(medv ~ rad*chas, data = Boston)
anova(model_rad_chas)

#(d)
m0 = lm(medv[chas==0] ~ lstat[chas==0], data=Boston)
m1 = lm(medv[chas==1] ~ lstat[chas==1], data=Boston)
lstat_seq <- seq(min(Boston$lstat), max(Boston$lstat), length.out = 100)
plot(Boston$lstat[Boston$chas==0], Boston$medv[Boston$chas==0], pch = 1,col=1,xlab="lstat",ylab="medv")
points(Boston$lstat[Boston$chas==1], Boston$medv[Boston$chas==1], col = 2, pch = 19)
abline(m0,col=1)
abline(m1,col=2)
legend("topright",legend=c("chas=0","chas=1"),col=1:2, lwd = 2, cex=1)
m3 = lm(medv ~ lstat*chas, data=Boston)
anova(m3)